Repository jminie-o8o/Home-Rent-App, pull requests merged in 2022-08, with the labels that each got.

#11 [backend] oauth 로그아웃 기능 추가
  BE/house/src/main/java/com/nextsquad/house/config/webConfig/LoginInterceptor.java
  BE/house/src/main/java/com/nextsquad/house/config/webConfig/webConfig.java
  BE/house/src/main/java/com/nextsquad/house/controller/LoginController.java
  BE/house/src/main/java/com/nextsquad/house/controller/LogoutController.java
  BE/house/src/main/java/com/nextsquad/house/dto/GeneralResponseDto.java
  BE/house/src/main/java/com/nextsquad/house/service/LoginService.java
  BE/house/src/main/java/com/nextsquad/house/service/LogoutService.java
  BE/house/src/main/java/com/nextsquad/house/service/RedisService.java
Labels: Backend, feature

#12 [backend] 사용자 정보 조회 기능 구현
  BE/house/src/main/java/com/nextsquad/house/controller/UserController.java
  BE/house/src/main/java/com/nextsquad/house/dto/UserResponseDto.java
  BE/house/src/main/java/com/nextsquad/house/service/UserService.java
Labels: Backend, feature

#3 [Android] ktlint 적용
  android/.idea/codeStyles/Project.xml
  android/.idea/codeStyles/codeStyleConfig.xml
  android/.idea/gradle.xml
  android/.idea/inspectionProfiles/ktlint.xml
  android/.idea/inspectionProfiles/profiles_settings.xml
  android/.idea/misc.xml
  android/app/build.gradle
  android/app/src/androidTest/java/com/example/home_rent_app/ExampleInstrumentedTest.kt
  android/app/src/main/java/com/example/home_rent_app/MainActivity.kt
  android/app/src/test/java/com/example/home_rent_app/ExampleUnitTest.kt
  android/build.gradle
  android/settings.gradle
Labels: Android, feature

#25 [backend] Exception Handler 구현
  BE/house/src/main/java/com/nextsquad/house/exception/RuntimeExceptionHandler.java
  BE/house/src/main/java/com/nextsquad/house/service/UserService.java
Labels: Backend, feature

#29 [backend] 사용자 정보 수정 기능 구현
  BE/house/src/main/java/com/nextsquad/house/controller/UserController.java
  BE/house/src/main/java/com/nextsquad/house/domain/user/Gender.java
  BE/house/src/main/java/com/nextsquad/house/domain/user/User.java
  BE/house/src/main/java/com/nextsquad/house/dto/UserInfoDto.java
  BE/house/src/main/java/com/nextsquad/house/dto/UserResponseDto.java
  BE/house/src/main/java/com/nextsquad/house/service/UserService.java
Labels: Backend, feature

#30 [Android] 로그인 페이지 UI 및 카카오 OAuth 인가코드 받기
  .idea/workspace.xml
  android/.github/PULL_REQUEST_TEMPLATE.md
  android/.gitignore
  android/.idea/.name
  android/.idea/compiler.xml
  android/.idea/gradle.xml
  android/.idea/misc.xml
  android/.idea/vcs.xml
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/example/home_rent_app/ui/HomeActivity.kt
  android/app/src/main/java/com/example/home_rent_app/ui/LoginActivity.kt
  android/app/src/main/java/com/example/home_rent_app/ui/bookmark/BookmarkFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/chatting/ChattingFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/home/HomeFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/login/KakaoWebViewFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/login/LoginFragment.kt
  android/app/src/main/res/layout/activity_home.xml
  android/app/src/main/res/layout/activity_login.xml
  android/app/src/main/res/layout/fragment_kakao_web_view.xml
  android/app/src/main/res/layout/fragment_login.xml
  android/app/src/main/res/layout/fragment_profile.xml
  android/app/src/main/res/navigation/login_nav_graph.xml
  android/app/src/main/res/values/colors.xml
  android/build.gradle
Labels: Android, feature

#35 [Android] MVVM 패턴 적용 및 Hilt 적용해서 AccessToken 가져오기
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/example/home_rent_app/data/api/LoginApi.kt
  android/app/src/main/java/com/example/home_rent_app/data/api/RetrofitInstance.kt
  android/app/src/main/java/com/example/home_rent_app/data/model/KakaoOauthRequest.kt
  android/app/src/main/java/com/example/home_rent_app/data/model/OAuthTokenResponse.kt
  android/app/src/main/java/com/example/home_rent_app/data/repository/login/LoginRepository.kt
  android/app/src/main/java/com/example/home_rent_app/data/repository/login/LoginRepositoryImpl.kt
  android/app/src/main/java/com/example/home_rent_app/ui/LoginActivity.kt
  android/app/src/main/java/com/example/home_rent_app/ui/login/KakaoWebViewFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/login/LoginFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/viewmodel/LoginViewModel.kt
  android/app/src/main/java/com/example/home_rent_app/util/MainApplication.kt
  android/app/src/main/java/com/example/home_rent_app/util/RepositoryModule.kt
  android/build.gradle
Labels: Android, feature

#37 [Android] DataStore 설정
  android/app/build.gradle
  android/app/src/main/java/com/example/home_rent_app/data/api/RetrofitInstance.kt
  android/app/src/main/java/com/example/home_rent_app/data/repository/login/LoginRepository.kt
  android/app/src/main/java/com/example/home_rent_app/data/repository/login/LoginRepositoryImpl.kt
  android/app/src/main/java/com/example/home_rent_app/ui/HomeActivity.kt
  android/app/src/main/java/com/example/home_rent_app/ui/LoginActivity.kt
  android/app/src/main/java/com/example/home_rent_app/ui/bookmark/BookmarkFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/chatting/ChattingFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/home/HomeFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/login/KakaoWebViewFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/login/LoginFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/profile/ProfileFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/viewmodel/LoginViewModel.kt
  android/app/src/main/java/com/example/home_rent_app/util/Constants.kt
Labels: Android, feature

#39 [Android] feat: AppSession 생성과 인터셉터 구현
  android/app/src/main/java/com/example/home_rent_app/data/AuthInterceptor.kt
  android/app/src/main/java/com/example/home_rent_app/data/api/LoginApi.kt
  android/app/src/main/java/com/example/home_rent_app/data/dto/OAuthTokenResponse.kt
  android/app/src/main/java/com/example/home_rent_app/data/model/JWT.kt
  android/app/src/main/java/com/example/home_rent_app/data/model/OAuthTokenResponse.kt
  android/app/src/main/java/com/example/home_rent_app/data/repository/login/LoginRepository.kt
  android/app/src/main/java/com/example/home_rent_app/data/repository/login/LoginRepositoryImpl.kt
  android/app/src/main/java/com/example/home_rent_app/util/AppSession.kt
Labels: Android

#40 [Android] 로그인 프로필 UI 구현 및 앨범 권한, 앨범 이미지 업로드 구현
  android/.idea/misc.xml
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/example/home_rent_app/data/repository/login/LoginRepository.kt
  android/app/src/main/java/com/example/home_rent_app/data/repository/login/LoginRepositoryImpl.kt
  android/app/src/main/java/com/example/home_rent_app/ui/LoginActivity.kt
  android/app/src/main/java/com/example/home_rent_app/ui/login/LoginFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/loginprofile/LoginProfileFragment.kt
  android/app/src/main/res/drawable/custom_button_background.xml
  android/app/src/main/res/drawable/default_profile_image.png
  android/app/src/main/res/layout/fragment_login_profile.xml
  android/app/src/main/res/navigation/login_nav_graph.xml
  android/app/src/main/res/values-night/themes.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/styles.xml
  android/app/src/main/res/values/themes.xml
Labels: Android, feature

#42 [backend] 양도 글 작성 기능
  BE/house/build.gradle
  BE/house/src/main/java/com/nextsquad/house/controller/FileUploadController.java
  BE/house/src/main/java/com/nextsquad/house/controller/RentArticleController.java
  BE/house/src/main/java/com/nextsquad/house/domain/house/ArticleStatus.java
  BE/house/src/main/java/com/nextsquad/house/domain/house/ContractType.java
  BE/house/src/main/java/com/nextsquad/house/domain/house/Facility.java
  BE/house/src/main/java/com/nextsquad/house/domain/house/HouseImage.java
  BE/house/src/main/java/com/nextsquad/house/domain/house/HouseType.java
  BE/house/src/main/java/com/nextsquad/house/domain/house/RentArticle.java
  BE/house/src/main/java/com/nextsquad/house/domain/house/RentArticleFacility.java
  BE/house/src/main/java/com/nextsquad/house/dto/RentArticleCreationRequest.java
  BE/house/src/main/java/com/nextsquad/house/dto/RentArticleCreationResponse.java
  BE/house/src/main/java/com/nextsquad/house/exception/RuntimeExceptionHandler.java
  BE/house/src/main/java/com/nextsquad/house/repository/FacilityRepository.java
  BE/house/src/main/java/com/nextsquad/house/repository/HouseImageRepository.java
  BE/house/src/main/java/com/nextsquad/house/repository/RentArticleFacilityRepository.java
  BE/house/src/main/java/com/nextsquad/house/repository/RentArticleRepository.java
  BE/house/src/main/java/com/nextsquad/house/service/FileUploadService.java
  BE/house/src/main/java/com/nextsquad/house/service/RentArticleService.java
  BE/house/src/main/resources/application.yml
  BE/house/src/main/resources/data.sql
  BE/house/src/test/java/com/nextsquad/house/login/jwt/JwtProviderTest.java
Labels: Backend, feature

#44 [backend] 양도 글 안전시설 추가 기능 구현
  BE/house/src/main/java/com/nextsquad/house/domain/house/RentArticle.java
  BE/house/src/main/java/com/nextsquad/house/domain/house/RentArticleSecurityFacility.java
  BE/house/src/main/java/com/nextsquad/house/domain/house/SecurityFacility.java
  BE/house/src/main/java/com/nextsquad/house/dto/RentArticleCreationRequest.java
  BE/house/src/main/java/com/nextsquad/house/repository/FacilityInHomeRepository.java
  BE/house/src/main/java/com/nextsquad/house/repository/SecurityInHomeRepository.java
  BE/house/src/main/java/com/nextsquad/house/repository/SecurityRepository.java
  BE/house/src/main/java/com/nextsquad/house/service/RentArticleService.java
  BE/house/src/main/resources/data.sql
Labels: Backend, feature

#47 [backend] 양도글 조회 기능 구현
  BE/house/src/main/java/com/nextsquad/house/controller/RentArticleController.java
  BE/house/src/main/java/com/nextsquad/house/domain/house/Facility.java
  BE/house/src/main/java/com/nextsquad/house/domain/house/HouseImage.java
  BE/house/src/main/java/com/nextsquad/house/domain/house/RentArticleFacility.java
  BE/house/src/main/java/com/nextsquad/house/domain/house/RentArticleSecurityFacility.java
  BE/house/src/main/java/com/nextsquad/house/domain/house/SecurityFacility.java
  BE/house/src/main/java/com/nextsquad/house/dto/RentArticleResponse.java
  BE/house/src/main/java/com/nextsquad/house/service/RentArticleService.java
Labels: Backend, feature

#49 [backend] 양도 글 목록 보기 구현
  BE/house/src/main/java/com/nextsquad/house/controller/RentArticleController.java
  BE/house/src/main/java/com/nextsquad/house/domain/house/RentArticle.java
  BE/house/src/main/java/com/nextsquad/house/dto/RentArticleCreationRequest.java
  BE/house/src/main/java/com/nextsquad/house/dto/RentArticleListElement.java
  BE/house/src/main/java/com/nextsquad/house/dto/RentArticleListResponse.java
  BE/house/src/main/java/com/nextsquad/house/service/RentArticleService.java
Labels: Backend, feature

#52 [backend] 상세글 보기, 글 목록 보기에 필드 추가
  BE/house/src/main/java/com/nextsquad/house/domain/house/RentArticle.java
  BE/house/src/main/java/com/nextsquad/house/dto/RentArticleListElement.java
  BE/house/src/main/java/com/nextsquad/house/dto/RentArticleResponse.java
  BE/house/src/main/java/com/nextsquad/house/service/RentArticleService.java
Labels: Backend, refactor

#50 [Android] STEP 1 페이지 구현
  android/.idea/misc.xml
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/example/home_rent_app/ui/transfer/TransferActivity.kt
  android/app/src/main/java/com/example/home_rent_app/ui/transfer/TransferViewModel.kt
  android/app/src/main/java/com/example/home_rent_app/ui/transfer/step1/HomeDescriptionFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/transfer/step2/PicChoiceFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/transfer/step3/AddressSearchFragment.kt
  android/app/src/main/java/com/example/home_rent_app/util/LifecycleExtension.kt
  android/app/src/main/java/com/example/home_rent_app/util/Logger.kt
  android/app/src/main/java/com/example/home_rent_app/util/RentType.kt
  android/app/src/main/java/com/example/home_rent_app/util/RoomType.kt
  android/app/src/main/java/com/example/home_rent_app/util/TransferBindingAdapter.kt
  android/app/src/main/res/color/chip_selector.xml
  android/app/src/main/res/color/chip_stroke.xml
  android/app/src/main/res/color/chip_text.xml
  android/app/src/main/res/drawable/ic_close.xml
  android/app/src/main/res/drawable/shape_title_edittext.xml
  android/app/src/main/res/layout/activity_transfer.xml
  android/app/src/main/res/layout/fragment_address_search.xml
  android/app/src/main/res/layout/fragment_home_description.xml
  android/app/src/main/res/layout/fragment_pic_choice.xml
  android/app/src/main/res/navigation/transfer_graph.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/themes.xml
Labels: Android

#58 [backend] RentArticle 필드 추가 및 양도글 찜 목록 조회
  BE/house/src/main/java/com/nextsquad/house/controller/UserController.java
  BE/house/src/main/java/com/nextsquad/house/domain/house/RentArticle.java
  BE/house/src/main/java/com/nextsquad/house/dto/RentArticleCreationRequest.java
  BE/house/src/main/java/com/nextsquad/house/dto/RentArticleListElement.java
  BE/house/src/main/java/com/nextsquad/house/dto/RentArticleResponse.java
  BE/house/src/main/java/com/nextsquad/house/dto/bookmark/RentBookmarkElement.java
  BE/house/src/main/java/com/nextsquad/house/dto/bookmark/RentBookmarkListResponse.java
  BE/house/src/main/java/com/nextsquad/house/service/RentArticleService.java
  BE/house/src/main/java/com/nextsquad/house/service/UserService.java
  BE/house/src/main/resources/data.sql
Labels: Backend, feature, refactor

#60 [backend] 양도 글 수정 기능 구현
  BE/house/src/main/java/com/nextsquad/house/controller/RentArticleController.java
  BE/house/src/main/java/com/nextsquad/house/domain/house/RentArticle.java
  BE/house/src/main/java/com/nextsquad/house/dto/RentArticleRequest.java
  BE/house/src/main/java/com/nextsquad/house/repository/FacilityInHomeRepository.java
  BE/house/src/main/java/com/nextsquad/house/repository/HouseImageRepository.java
  BE/house/src/main/java/com/nextsquad/house/repository/SecurityInHomeRepository.java
  BE/house/src/main/java/com/nextsquad/house/service/RentArticleService.java
Labels: Backend, feature

#62 [backend] 양수 글 작성 기능 구현
  BE/house/src/main/java/com/nextsquad/house/controller/RentArticleController.java
  BE/house/src/main/java/com/nextsquad/house/controller/WantedArticleController.java
  BE/house/src/main/java/com/nextsquad/house/domain/house/WantedArticle.java
  BE/house/src/main/java/com/nextsquad/house/dto/wantedArticle/SavedWantedArticleResponse.java
  BE/house/src/main/java/com/nextsquad/house/dto/wantedArticle/WantedArticleRequest.java
  BE/house/src/main/java/com/nextsquad/house/repository/WantedArticleRepository.java
  BE/house/src/main/java/com/nextsquad/house/service/WantedArticleService.java
Labels: Backend, feature

#64 [backend] 회원 가입 시 닉네임 중복 체크 기능 구현
  BE/house/src/main/java/com/nextsquad/house/controller/UserController.java
  BE/house/src/main/java/com/nextsquad/house/dto/user/DuplicationCheckResponse.java
  BE/house/src/main/java/com/nextsquad/house/login/userinfo/UserInfo.java
  BE/house/src/main/java/com/nextsquad/house/repository/UserRepository.java
  BE/house/src/main/java/com/nextsquad/house/service/UserService.java
Labels: Backend, feature

#66 [backend] 양수글 목록 보기 기능 구현
  BE/house/src/main/java/com/nextsquad/house/controller/WantedArticleController.java
  BE/house/src/main/java/com/nextsquad/house/dto/wantedArticle/WantedArticleElementResponse.java
  BE/house/src/main/java/com/nextsquad/house/dto/wantedArticle/WantedArticleListResponse.java
  BE/house/src/main/java/com/nextsquad/house/repository/WantedArticleRepository.java
  BE/house/src/main/java/com/nextsquad/house/service/WantedArticleService.java
Labels: Backend, feature

#68 Feat: 양수 글 상세보기 기능 추가, 양수 글 생성 시 수정일 업데이트 버그 수정
  BE/house/src/main/java/com/nextsquad/house/controller/WantedArticleController.java
  BE/house/src/main/java/com/nextsquad/house/dto/UserInfoDto.java
  BE/house/src/main/java/com/nextsquad/house/dto/wantedArticle/WantedArticleResponse.java
  BE/house/src/main/java/com/nextsquad/house/service/WantedArticleService.java
Labels: Backend, feature

#71 Feat: 양수 글 수정 기능 구현
  BE/house/src/main/java/com/nextsquad/house/controller/WantedArticleController.java
  BE/house/src/main/java/com/nextsquad/house/domain/house/WantedArticle.java
  BE/house/src/main/java/com/nextsquad/house/service/WantedArticleService.java
Labels: Backend, feature

#72 [backend] 양수글 삭제 기능 구현
  BE/house/src/main/java/com/nextsquad/house/controller/WantedArticleController.java
  BE/house/src/main/java/com/nextsquad/house/domain/house/WantedArticle.java
  BE/house/src/main/java/com/nextsquad/house/repository/WantedArticleRepository.java
  BE/house/src/main/java/com/nextsquad/house/service/WantedArticleService.java
Labels: Backend, feature

#54 [Android] FEAT : 제목 글자 수 보여주는 기능 추가
  android/app/src/main/java/com/example/home_rent_app/ui/transfer/TransferActivity.kt
  android/app/src/main/java/com/example/home_rent_app/ui/transfer/step1/HomeDescriptionFragment.kt
  android/app/src/main/res/layout/fragment_home_description.xml
  android/app/src/main/res/values/strings.xml
Labels: Android

#76 [backend] 양수글 찜하기 기능 구현
  BE/house/src/main/java/com/nextsquad/house/controller/WantedArticleController.java
  BE/house/src/main/java/com/nextsquad/house/domain/house/WantedArticle.java
  BE/house/src/main/java/com/nextsquad/house/domain/house/WantedArticleBookmark.java
  BE/house/src/main/java/com/nextsquad/house/dto/wantedArticle/WantedArticleResponse.java
  BE/house/src/main/java/com/nextsquad/house/repository/WantedArticleBookmarkRepository.java
  BE/house/src/main/java/com/nextsquad/house/service/WantedArticleService.java
Labels: Backend, feature

#78 Feature delete wanted bookmark
  BE/house/src/main/java/com/nextsquad/house/controller/WantedArticleController.java
  BE/house/src/main/java/com/nextsquad/house/repository/RentArticleBookmarkRepository.java
  BE/house/src/main/java/com/nextsquad/house/repository/WantedArticleBookmarkRepository.java
  BE/house/src/main/java/com/nextsquad/house/service/RentArticleService.java
  BE/house/src/main/java/com/nextsquad/house/service/WantedArticleService.java
Labels: Backend, feature, fix

#80 feat: 찜하기(양수글) 목록 보기 기능 구현
  BE/house/src/main/java/com/nextsquad/house/controller/UserController.java
  BE/house/src/main/java/com/nextsquad/house/dto/wantedArticle/WantedArticleElementResponse.java
  BE/house/src/main/java/com/nextsquad/house/repository/WantedArticleBookmarkRepository.java
  BE/house/src/main/java/com/nextsquad/house/service/UserService.java
Labels: Backend, feature

#83 [Android] DataStore 이용하여 자동로그인 구현 및 Flow 확장함수를 이용하여 좋아요 다중클릭 방지
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/example/home_rent_app/ui/HomeActivity.kt
  android/app/src/main/java/com/example/home_rent_app/ui/LoginActivity.kt
  android/app/src/main/java/com/example/home_rent_app/ui/login/KakaoWebViewFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/login/NaverWebViewFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/viewmodel/LoginViewModel.kt
  android/app/src/main/java/com/example/home_rent_app/ui/wanthome/WantHomeActivity.kt
  android/app/src/main/java/com/example/home_rent_app/ui/wanthome/detail/WantHomeDetailFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/wanthome/step1/WantHomeFirstStepFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/wanthome/step2/WantHomeSecondStepFragment.kt
  android/app/src/main/java/com/example/home_rent_app/util/Extention.kt
  android/app/src/main/java/com/example/home_rent_app/util/FlowExtention.kt
  android/app/src/main/res/drawable/heart_selector.xml
  android/app/src/main/res/layout/activity_take_home.xml
  android/app/src/main/res/layout/fragment_want_home_detail.xml
  android/app/src/main/res/layout/fragment_want_home_first_step.xml
  android/app/src/main/res/layout/fragment_want_home_second_step.xml
  android/app/src/main/res/navigation/want_home_nav_graph.xml
Labels: Android, feature

#85 [backend] 내가 쓴 양수글 목록 보기 기능
  BE/house/src/main/java/com/nextsquad/house/controller/UserController.java
  BE/house/src/main/java/com/nextsquad/house/domain/user/User.java
  BE/house/src/main/java/com/nextsquad/house/repository/WantedArticleRepository.java
  BE/house/src/main/java/com/nextsquad/house/service/UserService.java
Labels: Backend, feature

#87 [backend] 사용자의 양도 게시글 가져오기 기능 구현
  BE/house/src/main/java/com/nextsquad/house/config/webConfig/webConfig.java
  BE/house/src/main/java/com/nextsquad/house/controller/UserController.java
  BE/house/src/main/java/com/nextsquad/house/domain/user/User.java
  BE/house/src/main/java/com/nextsquad/house/service/UserService.java
Labels: Backend, feature

#88 [Android] SplashScreen을 이용하여 UI 개선
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/example/home_rent_app/data/repository/login/LoginRepositoryImpl.kt
  android/app/src/main/java/com/example/home_rent_app/ui/LoginActivity.kt
  android/app/src/main/java/com/example/home_rent_app/ui/SplashScreenActivity.kt
  android/app/src/main/java/com/example/home_rent_app/ui/login/KakaoWebViewFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/login/NaverWebViewFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/transfer/TransferActivity.kt
  android/app/src/main/java/com/example/home_rent_app/ui/transfer/TransferViewModel.kt
  android/app/src/main/java/com/example/home_rent_app/ui/transfer/step1/HomeDescriptionFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/transfer/step2/PicChoiceFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/transfer/step3/AddressSearchFragment.kt
  android/app/src/main/java/com/example/home_rent_app/util/RentType.kt
  android/app/src/main/java/com/example/home_rent_app/util/RoomType.kt
  android/app/src/main/java/com/example/home_rent_app/util/TransferBindingAdapter.kt
  android/app/src/main/res/layout/activity_splash_screen.xml
  android/app/src/main/res/values-night/themes.xml
  android/app/src/main/res/values/themes.xml
Labels: Android, refactor

#90 [backend] 페이징 처리 (양수글, 유저 관련)
  BE/house/src/main/java/com/nextsquad/house/controller/UserController.java
  BE/house/src/main/java/com/nextsquad/house/controller/WantedArticleController.java
  BE/house/src/main/java/com/nextsquad/house/dto/RentArticleListResponse.java
  BE/house/src/main/java/com/nextsquad/house/dto/wantedArticle/WantedArticleListResponse.java
  BE/house/src/main/java/com/nextsquad/house/repository/RentArticleBookmarkRepository.java
  BE/house/src/main/java/com/nextsquad/house/repository/RentArticleRepository.java
  BE/house/src/main/java/com/nextsquad/house/repository/WantedArticleBookmarkRepository.java
  BE/house/src/main/java/com/nextsquad/house/repository/WantedArticleRepository.java
  BE/house/src/main/java/com/nextsquad/house/service/UserService.java
  BE/house/src/main/java/com/nextsquad/house/service/WantedArticleService.java
Labels: Backend, refactor

#92 [Android] FEAT: 사진 업로드 구현
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/example/home_rent_app/data/AuthInterceptor.kt
  android/app/src/main/java/com/example/home_rent_app/data/api/RetrofitInstance.kt
  android/app/src/main/java/com/example/home_rent_app/data/api/TransferApi.kt
  android/app/src/main/java/com/example/home_rent_app/data/datasource/transfer/TransferDataSource.kt
  android/app/src/main/java/com/example/home_rent_app/data/datasource/transfer/TransferDataSourceImpl.kt
  android/app/src/main/java/com/example/home_rent_app/data/dto/ImageUrlDTO.kt
  android/app/src/main/java/com/example/home_rent_app/data/model/ImageUrl.kt
  android/app/src/main/java/com/example/home_rent_app/data/model/RoomPicture.kt
  android/app/src/main/java/com/example/home_rent_app/data/repository/login/LoginRepository.kt
  android/app/src/main/java/com/example/home_rent_app/data/repository/login/LoginRepositoryImpl.kt
  android/app/src/main/java/com/example/home_rent_app/data/repository/transfer/TransferRepository.kt
  android/app/src/main/java/com/example/home_rent_app/data/repository/transfer/TransferRepositoryImpl.kt
  android/app/src/main/java/com/example/home_rent_app/di/DataSourceModule.kt
  android/app/src/main/java/com/example/home_rent_app/di/RepositoryModule.kt
  android/app/src/main/java/com/example/home_rent_app/ui/ShootOrAlbumDialog.kt
  android/app/src/main/java/com/example/home_rent_app/ui/custom/MainImageView.kt
  android/app/src/main/java/com/example/home_rent_app/ui/custom/PriceEditText.kt
  android/app/src/main/java/com/example/home_rent_app/ui/home/HomeFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/transfer/TransferActivity.kt
  android/app/src/main/java/com/example/home_rent_app/ui/transfer/TransferViewModel.kt
  android/app/src/main/java/com/example/home_rent_app/ui/transfer/step1/HomeDescriptionFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/transfer/step2/PicAdapter.kt
  android/app/src/main/java/com/example/home_rent_app/ui/transfer/step2/PicChoiceFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/viewmodel/LoginViewModel.kt
  android/app/src/main/java/com/example/home_rent_app/util/BitmapCreator.kt
  android/app/src/main/java/com/example/home_rent_app/util/FileController.kt
  android/app/src/main/java/com/example/home_rent_app/util/MoneyFormat.kt
  android/app/src/main/java/com/example/home_rent_app/util/PicControlListener.kt
  android/app/src/main/java/com/example/home_rent_app/util/ShadowBuilder.kt
  android/app/src/main/java/com/example/home_rent_app/util/UiState.kt
  android/app/src/main/res/drawable/ic_camera.xml
  android/app/src/main/res/drawable/shape_dialog.xml
  android/app/src/main/res/drawable/shape_remove.xml
  android/app/src/main/res/layout/dialog_shoot_or_album.xml
  android/app/src/main/res/layout/fragment_home.xml
  android/app/src/main/res/layout/fragment_home_description.xml
  android/app/src/main/res/layout/fragment_pic_choice.xml
  android/app/src/main/res/layout/item_main_pic.xml
  android/app/src/main/res/layout/item_room_pic.xml
  android/app/src/main/res/navigation/transfer_graph.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
Labels: Android

#97 [backend] 양수/양도 글 검색 및 정렬 처리
  BE/house/build.gradle
  BE/house/src/main/java/com/nextsquad/house/config/JpaQueryConfig.java
  BE/house/src/main/java/com/nextsquad/house/controller/RentArticleController.java
  BE/house/src/main/java/com/nextsquad/house/controller/WantedArticleController.java
  BE/house/src/main/java/com/nextsquad/house/domain/house/RentArticle.java
  BE/house/src/main/java/com/nextsquad/house/dto/SearchConditionDto.java
  BE/house/src/main/java/com/nextsquad/house/repository/CustomRentArticleRepository.java
  BE/house/src/main/java/com/nextsquad/house/repository/CustomRentArticleRepositoryImpl.java
  BE/house/src/main/java/com/nextsquad/house/repository/CustomWantedArticleRepository.java
  BE/house/src/main/java/com/nextsquad/house/repository/CustomWantedArticleRepositoryImpl.java
  BE/house/src/main/java/com/nextsquad/house/repository/RentArticleRepository.java
  BE/house/src/main/java/com/nextsquad/house/repository/WantedArticleRepository.java
  BE/house/src/main/java/com/nextsquad/house/service/RentArticleService.java
  BE/house/src/main/java/com/nextsquad/house/service/WantedArticleService.java
Labels: Backend, feature

#99 [backend] 예외 처리
  BE/house/src/main/java/com/nextsquad/house/config/webConfig/LoginInterceptor.java
  BE/house/src/main/java/com/nextsquad/house/exception/ArticleNotFoundException.java
  BE/house/src/main/java/com/nextsquad/house/exception/BookmarkNotFoundException.java
  BE/house/src/main/java/com/nextsquad/house/exception/OauthClientNotFoundException.java
  BE/house/src/main/java/com/nextsquad/house/exception/RuntimeExceptionHandler.java
  BE/house/src/main/java/com/nextsquad/house/exception/UserNotFoundException.java
  BE/house/src/main/java/com/nextsquad/house/service/LoginService.java
  BE/house/src/main/java/com/nextsquad/house/service/RentArticleService.java
  BE/house/src/main/java/com/nextsquad/house/service/UserService.java
  BE/house/src/main/java/com/nextsquad/house/service/WantedArticleService.java
Labels: Backend, feature

#100 [Android] 프로필 중복 확인 및 프로필 계정 만들지 않았을 시 앱 재시작하면 로그인 페이지로 이동
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/example/home_rent_app/data/AuthInterceptor.kt
  android/app/src/main/java/com/example/home_rent_app/data/api/LoginProfileApi.kt
  android/app/src/main/java/com/example/home_rent_app/data/api/RetrofitInstance.kt
  android/app/src/main/java/com/example/home_rent_app/data/datasource/transfer/TransferDataSourceImpl.kt
  android/app/src/main/java/com/example/home_rent_app/data/dto/NickNameCheckDTO.kt
  android/app/src/main/java/com/example/home_rent_app/data/model/NickNameCheck.kt
  android/app/src/main/java/com/example/home_rent_app/data/repository/login/LoginRepository.kt
  android/app/src/main/java/com/example/home_rent_app/data/repository/login/LoginRepositoryImpl.kt
  android/app/src/main/java/com/example/home_rent_app/data/repository/loginProfile/LoginProfileRepository.kt
  android/app/src/main/java/com/example/home_rent_app/data/repository/loginProfile/LoginProfileRepositoryImpl.kt
  android/app/src/main/java/com/example/home_rent_app/data/repository/transfer/TransferRepositoryImpl.kt
  android/app/src/main/java/com/example/home_rent_app/ui/SplashScreenActivity.kt
  android/app/src/main/java/com/example/home_rent_app/ui/loginprofile/LoginProfileFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/transfer/TransferViewModel.kt
  android/app/src/main/java/com/example/home_rent_app/ui/transfer/step1/HomeDescriptionFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/transfer/step2/PicAdapter.kt
  android/app/src/main/java/com/example/home_rent_app/ui/transfer/step2/PicChoiceFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/transfer/step3/AddressSearchFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/viewmodel/LoginProfileViewModel.kt
  android/app/src/main/java/com/example/home_rent_app/ui/viewmodel/LoginViewModel.kt
  android/app/src/main/java/com/example/home_rent_app/util/FileController.kt
  android/app/src/main/java/com/example/home_rent_app/util/RepositoryModule.kt
  android/app/src/main/java/com/example/home_rent_app/util/ShadowBuilder.kt
Labels: Android, feature

#101 [Android] JWT 담기지 않던 이슈 및 뒤로가기를 눌러도 앱이 종료되지 않던 이슈 해결
  android/app/src/main/java/com/example/home_rent_app/ui/LoginActivity.kt
  android/app/src/main/java/com/example/home_rent_app/ui/SplashScreenActivity.kt
  android/app/src/main/java/com/example/home_rent_app/ui/viewmodel/LoginViewModel.kt
  android/app/src/main/java/com/example/home_rent_app/ui/viewmodel/WantHomeViewModel.kt
  android/app/src/main/java/com/example/home_rent_app/ui/wanthome/step2/WantHomeSecondStepFragment.kt
  android/app/src/main/java/com/example/home_rent_app/util/Location.kt
  android/app/src/main/java/com/example/home_rent_app/util/LocationBindingAdapter.kt
  android/app/src/main/res/layout/fragment_want_home_first_step.xml
  android/app/src/main/res/layout/fragment_want_home_second_step.xml
Labels: Android, fix

#105 [Android] feat: 양수인 찾기, 방찾기 버튼 구현
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/example/home_rent_app/ui/findroom/FindRoomActivity.kt
  android/app/src/main/java/com/example/home_rent_app/ui/home/HomeFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/transfer/TransferActivity.kt
  android/app/src/main/java/com/example/home_rent_app/ui/transfer/step1/HomeDescriptionFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/transfer/step2/PicChoiceFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/viewmodel/TransferViewModel.kt
  android/app/src/main/res/layout/activity_find_room.xml
  android/app/src/main/res/layout/fragment_home.xml
  android/app/src/main/res/layout/fragment_home_description.xml
Labels: Android

#108 [Android] FEAT: 주소 검색 기능 구현
  android/app/src/main/java/com/example/home_rent_app/ui/loginprofile/LoginProfileFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/transfer/step2/PicChoiceFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/transfer/step3/AddressSearchFragment.kt
  android/app/src/main/res/layout/fragment_address_search.xml
Labels: Android

#112 [backend] 글 상세보기 및 JWT 토큰 발급 시 UserId 리턴
  BE/house/src/main/java/com/nextsquad/house/dto/JwtResponseDto.java
  BE/house/src/main/java/com/nextsquad/house/dto/UserInfoDto.java
  BE/house/src/main/java/com/nextsquad/house/service/LoginService.java
Labels: Backend, refactor

#113 [Android] 양수글 키워드 검색 부분 구현
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/example/home_rent_app/data/api/RetrofitInstance.kt
  android/app/src/main/java/com/example/home_rent_app/data/api/WantHomeResultApi.kt
  android/app/src/main/java/com/example/home_rent_app/data/dto/WantHomeResultDTO.kt
  android/app/src/main/java/com/example/home_rent_app/data/model/WantHomeResultRequest.kt
  android/app/src/main/java/com/example/home_rent_app/data/repository/wanthomeresult/WantHomeResultRepository.kt
  android/app/src/main/java/com/example/home_rent_app/data/repository/wanthomeresult/WantHomeResultRepositoryImpl.kt
  android/app/src/main/java/com/example/home_rent_app/di/RepositoryModule.kt
  android/app/src/main/java/com/example/home_rent_app/ui/LoginActivity.kt
  android/app/src/main/java/com/example/home_rent_app/ui/bookmark/BookmarkFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/bookmark/BookmarkGiveHomeFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/bookmark/BookmarkWantHomeFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/findroom/FindRoomActivity.kt
  android/app/src/main/java/com/example/home_rent_app/ui/home/HomeFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/loginprofile/LoginProfileFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/viewmodel/LoginProfileViewModel.kt
  android/app/src/main/java/com/example/home_rent_app/ui/viewmodel/LoginViewModel.kt
  android/app/src/main/java/com/example/home_rent_app/ui/viewmodel/WantHomeResultViewModel.kt
  android/app/src/main/java/com/example/home_rent_app/ui/wanthome/WantHomeActivity.kt
  android/app/src/main/java/com/example/home_rent_app/ui/wanthome/step2/WantHomeSecondStepFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/wanthomeresult/WantHomeResultActivity.kt
  android/app/src/main/java/com/example/home_rent_app/ui/wanthomeresult/WantHomeResultAdapter.kt
  android/app/src/main/java/com/example/home_rent_app/util/BookMarkViewPagerAdapter.kt
  android/app/src/main/java/com/example/home_rent_app/util/LocationBindingAdapter.kt
  android/app/src/main/java/com/example/home_rent_app/util/TextBindingAdapter.kt
  android/app/src/main/java/com/example/home_rent_app/util/TimeUtils.kt
  android/app/src/main/res/drawable/edittext_rounded_corner.xml
  android/app/src/main/res/drawable/ic_baseline_search_26.xml
  android/app/src/main/res/layout/activity_want_home_result.xml
  android/app/src/main/res/layout/fragment_bookmark.xml
  android/app/src/main/res/layout/fragment_bookmark_give_home.xml
  android/app/src/main/res/layout/fragment_bookmark_want_home.xml
  android/app/src/main/res/layout/fragment_want_home_second_step.xml
  android/app/src/main/res/layout/item_wanthome_result.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/styles.xml
Labels: Android, feature

#115 [Android] 양도글 검색과 집 리스트 화면 구현
  android/app/build.gradle
  android/app/src/androidTest/java/com/example/home_rent_app/FindRentTest.kt
  android/app/src/androidTest/java/com/example/home_rent_app/FindRoomViewModelTest.kt
  android/app/src/androidTest/java/com/example/home_rent_app/HomeTest.kt
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/example/home_rent_app/data/api/FindRoomApi.kt
  android/app/src/main/java/com/example/home_rent_app/data/datasource/findroom/FindRoomDataSource.kt
  android/app/src/main/java/com/example/home_rent_app/data/datasource/findroom/FindRoomDataSourceImpl.kt
  android/app/src/main/java/com/example/home_rent_app/data/repository/findroom/FindRoomRepository.kt
  android/app/src/main/java/com/example/home_rent_app/data/repository/findroom/FindRoomRepositoryImpl.kt
  android/app/src/main/java/com/example/home_rent_app/ui/chatting/ChattingFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/findroom/FindHomeActivity.kt
  android/app/src/main/java/com/example/home_rent_app/ui/findroom/HomeListAdapter.kt
  android/app/src/main/java/com/example/home_rent_app/ui/findroom/HomeThumbnailAdapter.kt
  android/app/src/main/java/com/example/home_rent_app/ui/home/HomeFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/viewmodel/FindRoomViewModel.kt
  android/app/src/main/java/com/example/home_rent_app/util/RoomListBindingAdapter.kt
  android/app/src/main/res/layout/activity_find_room.xml
  android/app/src/main/res/layout/fragment_chatting.xml
  android/app/src/main/res/layout/item_search_result.xml
  android/app/src/main/res/layout/item_thumbnail.xml
  android/app/src/main/res/values/strings.xml
  android/settings.gradle
Labels: Android

#118 [backend] 게시글 목록에서 북마크 여부 반환
  BE/house/src/main/java/com/nextsquad/house/controller/RentArticleController.java
  BE/house/src/main/java/com/nextsquad/house/controller/WantedArticleController.java
  BE/house/src/main/java/com/nextsquad/house/dto/RentArticleListElement.java
  BE/house/src/main/java/com/nextsquad/house/dto/wantedArticle/WantedArticleElementResponse.java
  BE/house/src/main/java/com/nextsquad/house/repository/RentArticleBookmarkRepository.java
  BE/house/src/main/java/com/nextsquad/house/repository/WantedArticleBookmarkRepository.java
  BE/house/src/main/java/com/nextsquad/house/repository/WantedArticleRepository.java
  BE/house/src/main/java/com/nextsquad/house/service/RentArticleService.java
  BE/house/src/main/java/com/nextsquad/house/service/WantedArticleService.java
Labels: Backend, refactor

#119 [Android] DataStore에 User 정보 저장 및, 기존 회원일 시 앱을 삭제하고 다시 로그인 하더라도 프로필 생성 페이지가 아닌 HomeActivity로 이동하도록 수정
  android/app/src/main/java/com/example/home_rent_app/data/api/FindRoomApi.kt
  android/app/src/main/java/com/example/home_rent_app/data/api/WantHomeResultApi.kt
  android/app/src/main/java/com/example/home_rent_app/data/datasource/findroom/FindRoomDataSourceImpl.kt
  android/app/src/main/java/com/example/home_rent_app/data/dto/OAuthTokenResponse.kt
  android/app/src/main/java/com/example/home_rent_app/data/dto/WantHouseBookMarkResponseDTO.kt
  android/app/src/main/java/com/example/home_rent_app/data/model/AddBookmarkRequest.kt
  android/app/src/main/java/com/example/home_rent_app/data/model/User.kt
  android/app/src/main/java/com/example/home_rent_app/data/repository/login/LoginRepository.kt
  android/app/src/main/java/com/example/home_rent_app/data/repository/login/LoginRepositoryImpl.kt
  android/app/src/main/java/com/example/home_rent_app/data/repository/wanthomeresult/WantHomeResultRepository.kt
  android/app/src/main/java/com/example/home_rent_app/data/repository/wanthomeresult/WantHomeResultRepositoryImpl.kt
  android/app/src/main/java/com/example/home_rent_app/ui/LoginActivity.kt
  android/app/src/main/java/com/example/home_rent_app/ui/login/KakaoWebViewFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/login/NaverWebViewFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/viewmodel/LoginViewModel.kt
  android/app/src/main/java/com/example/home_rent_app/ui/viewmodel/WantHomeResultViewModel.kt
  android/app/src/main/java/com/example/home_rent_app/ui/wanthomeresult/WantHomeResultActivity.kt
  android/app/src/main/java/com/example/home_rent_app/ui/wanthomeresult/WantHomeResultAdapter.kt
  android/app/src/main/java/com/example/home_rent_app/util/Constants.kt
  android/app/src/main/res/layout/activity_want_home_result.xml
  android/app/src/main/res/values/strings.xml
Labels: Android, feature

#120 [Android] UserSession 구현 및 로그인 이동 로직 수정
  android/app/src/main/java/com/example/home_rent_app/data/dto/OAuthTokenResponse.kt
  android/app/src/main/java/com/example/home_rent_app/data/model/User.kt
  android/app/src/main/java/com/example/home_rent_app/data/repository/login/LoginRepository.kt
  android/app/src/main/java/com/example/home_rent_app/data/repository/login/LoginRepositoryImpl.kt
  android/app/src/main/java/com/example/home_rent_app/ui/login/KakaoWebViewFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/viewmodel/LoginViewModel.kt
  android/app/src/main/java/com/example/home_rent_app/util/Constants.kt
  android/app/src/main/java/com/example/home_rent_app/util/UserSession.kt
Labels: Android, feature

#121 [Android] 카카오 로그인이 2번 불러지던 이슈 해결
  android/app/src/main/java/com/example/home_rent_app/data/dto/OAuthTokenResponse.kt
  android/app/src/main/java/com/example/home_rent_app/data/repository/login/LoginRepository.kt
  android/app/src/main/java/com/example/home_rent_app/data/repository/login/LoginRepositoryImpl.kt
  android/app/src/main/java/com/example/home_rent_app/ui/login/KakaoWebViewFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/viewmodel/LoginViewModel.kt
Labels: Android, fix

#125 [Android] feat: 토큰 만료시 재요청 기능 구현 (테스트 진행 중)
  android/app/src/main/java/com/example/home_rent_app/data/AuthInterceptor.kt
  android/app/src/main/java/com/example/home_rent_app/data/datasource/token/TokenDataSourceImpl.kt
  android/app/src/main/java/com/example/home_rent_app/data/repository/token/TokenRepositoryImpl.kt
  android/app/src/main/java/com/example/home_rent_app/di/DataSourceModule.kt
  android/app/src/main/java/com/example/home_rent_app/di/RepositoryModule.kt
  android/app/src/main/java/com/example/home_rent_app/ui/viewmodel/FindRoomViewModel.kt
Labels: Android

#127 [Android] 양도글 작성 상세 설명 UI 구현
  android/app/src/main/java/com/example/home_rent_app/data/AuthInterceptor.kt
  android/app/src/main/java/com/example/home_rent_app/data/RefreshInterceptor.kt
  android/app/src/main/java/com/example/home_rent_app/data/api/RetrofitInstance.kt
  android/app/src/main/java/com/example/home_rent_app/data/repository/refresh/RefreshRepositoryImpl.kt
  android/app/src/main/java/com/example/home_rent_app/ui/chatting/RentMessageListActivity.kt
  android/app/src/main/java/com/example/home_rent_app/ui/custom/PriceEditText.kt
  android/app/src/main/java/com/example/home_rent_app/ui/detail/DetailRentActivity.kt
  android/app/src/main/java/com/example/home_rent_app/ui/home/HomeFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/transfer/step3/AddressSearchFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/transfer/step4/RentHomeDescriptionFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/viewmodel/DetailHomeViewModel.kt
  android/app/src/main/java/com/example/home_rent_app/ui/viewmodel/FindRoomViewModel.kt
  android/app/src/main/java/com/example/home_rent_app/ui/viewmodel/LoginViewModel.kt
  android/app/src/main/res/layout/activity_find_room.xml
  android/app/src/main/res/layout/fragment_address_search.xml
  android/app/src/main/res/layout/fragment_home.xml
  android/app/src/main/res/layout/fragment_home_description.xml
  android/app/src/main/res/layout/fragment_rent_home_description.xml
  android/app/src/main/res/navigation/transfer_graph.xml
  android/app/src/main/res/values/attrs.xml
Labels: Android

#129 [backend] 북마크 중복 추가시 필터링, exception 메시지 수정
  BE/house/src/main/java/com/nextsquad/house/exception/BookmarkNotFoundException.java
  BE/house/src/main/java/com/nextsquad/house/exception/DuplicateBookmarkException.java
  BE/house/src/main/java/com/nextsquad/house/exception/OauthClientNotFoundException.java
  BE/house/src/main/java/com/nextsquad/house/exception/RuntimeExceptionHandler.java
  BE/house/src/main/java/com/nextsquad/house/service/RentArticleService.java
  BE/house/src/main/java/com/nextsquad/house/service/WantedArticleService.java
Labels: Backend, fix

#131 Fix default profile image
  BE/house/src/main/java/com/nextsquad/house/dto/KakaoUserInfoDto.java
  BE/house/src/main/java/com/nextsquad/house/login/jwt/JwtTokenType.java
  BE/house/src/main/java/com/nextsquad/house/login/oauth/KakaoOauthClient.java
  BE/house/src/main/java/com/nextsquad/house/login/userinfo/UserInfo.java
Labels: Backend, fix

#132 [Android] 안드로이드 지도 구현
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/example/home_rent_app/data/AuthInterceptor.kt
  android/app/src/main/java/com/example/home_rent_app/data/RefreshInterceptor.kt
  android/app/src/main/java/com/example/home_rent_app/data/api/MapApi.kt
  android/app/src/main/java/com/example/home_rent_app/data/api/RetrofitInstance.kt
  android/app/src/main/java/com/example/home_rent_app/data/datasource/login/LoginDataSourceImpl.kt
  android/app/src/main/java/com/example/home_rent_app/data/datasource/map/MapDataSource.kt
  android/app/src/main/java/com/example/home_rent_app/data/datasource/map/MapDataSourceImpl.kt
  android/app/src/main/java/com/example/home_rent_app/data/dto/MapResponseDTO.kt
  android/app/src/main/java/com/example/home_rent_app/data/model/MapResponse.kt
  android/app/src/main/java/com/example/home_rent_app/data/repository/map/MapRepository.kt
  android/app/src/main/java/com/example/home_rent_app/data/repository/map/MapRepositoryImpl.kt
  android/app/src/main/java/com/example/home_rent_app/di/DataSourceModule.kt
  android/app/src/main/java/com/example/home_rent_app/di/RepositoryModule.kt
  android/app/src/main/java/com/example/home_rent_app/ui/HomeActivity.kt
  android/app/src/main/java/com/example/home_rent_app/ui/custom/PriceEditText.kt
  android/app/src/main/java/com/example/home_rent_app/ui/detail/DetailRentActivity.kt
  android/app/src/main/java/com/example/home_rent_app/ui/transfer/step3/AddressSearchFragment.kt
  android/app/src/main/java/com/example/home_rent_app/ui/viewmodel/DetailHomeViewModel.kt
  android/app/src/main/java/com/example/home_rent_app/ui/viewmodel/TransferViewModel.kt
  android/app/src/main/java/com/example/home_rent_app/util/Constants.kt
  android/app/src/main/java/com/example/home_rent_app/util/MainApplication.kt
  android/app/src/main/res/drawable/appbar_heart_selector.xml
  android/app/src/main/res/drawable/ic_baseline_account_circle_24.xml
  android/app/src/main/res/drawable/ic_bed.xml
  android/app/src/main/res/drawable/ic_cctv.xml
  android/app/src/main/res/drawable/ic_circle_heart.xml
  android/app/src/main/res/drawable/ic_circle_heart_checked.xml
  android/app/src/main/res/drawable/ic_closet.xml
  android/app/src/main/res/drawable/ic_conditioner.xml
  android/app/src/main/res/drawable/ic_entrance.xml
  android/app/src/main/res/drawable/ic_expand_back.xml
  android/app/src/main/res/drawable/ic_marker.xml
  android/app/src/main/res/drawable/ic_refrigerator.xml
  android/app/src/main/res/drawable/ic_tv.xml
  android/app/src/main/res/drawable/ic_video_phone.xml
  android/app/src/main/res/drawable/ic_washer.xml
  android/app/src/main/res/drawable/shape_address_copy.xml
  android/app/src/main/res/drawable/shape_home_pic_count.xml
  android/app/src/main/res/layout/activity_detail_rent.xml
  android/app/src/main/res/layout/fragment_address_search.xml
  android/app/src/main/res/layout/fragment_rent_home_description.xml
  android/app/src/main/res/layout/item_icon.xml
  android/app/src/main/res/values/attrs.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/styles.xml
  android/app/src/main/res/values/themes.xml
  android/gradle.properties
  android/settings.gradle
Labels: Android
